[build]
builder = "nixpacks"
buildCommand = "cd DjangoReef && python -m pip install --upgrade pip && python -m pip install -r requirements.txt"

[deploy]
startCommand = "cd DjangoReef && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn PacificReef.wsgi"

[nixpacks]
provider = "python"
pythonVersion = "3.11"

[[services]]
name = "web"
[services.env]
PORT = "8000"
PYTHONPATH = "/app/DjangoReef"
