[build]
builder = "nixpacks"
buildCommand = "cd DjangoReef && pip install -r requirements.txt"

[deploy]
startCommand = "cd DjangoReef && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn PacificReef.wsgi"

[[services]]
name = "web"
[services.env]
PORT = "8000"
