# Generated by Django 5.2.7 on 2025-10-03 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='ID_ROL', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=50)),
            ],
            options={
                'db_table': 'MAIN_ROL',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(db_column='ID_USUARIO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=100, null=True)),
                ('apellido', models.CharField(db_column='APELLIDO', max_length=100, null=True)),
                ('correo', models.EmailField(db_column='CORREO', max_length=254, unique=True)),
                ('direccion', models.CharField(blank=True, db_column='DIRECCION', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, db_column='TELEFONO', max_length=20, null=True)),
                ('password', models.CharField(db_column='PASSWORD', max_length=255)),
                ('is_active', models.BooleanField(db_column='ACTIVO', default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rol', models.ForeignKey(db_column='ID_ROL', on_delete=django.db.models.deletion.PROTECT, to='reefapp.rol')),
            ],
            options={
                'db_table': 'USUARIO',
            },
        ),
    ]
