# Generated by Django 5.2 on 2025-10-04 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reefapp', '0002_remove_usuario_rol_remove_usuario_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicaHabitacion',
            fields=[
                ('id_caracteristica', models.AutoField(db_column='ID_CARACTERISTICA', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=100)),
                ('icono', models.CharField(blank=True, db_column='ICONO', max_length=50)),
            ],
            options={
                'db_table': 'CARACTERISTICA_HABITACION',
            },
        ),
        migrations.CreateModel(
            name='CategoriaHabitacion',
            fields=[
                ('id_categoria', models.AutoField(db_column='ID_CATEGORIA', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=50)),
                ('descripcion', models.TextField(db_column='DESCRIPCION')),
            ],
            options={
                'db_table': 'CATEGORIA_HABITACION',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='ID_ROL', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=50)),
            ],
            options={
                'db_table': 'MAIN_ROL',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(db_column='ID_USUARIO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=100, null=True)),
                ('apellido', models.CharField(db_column='APELLIDO', max_length=100, null=True)),
                ('correo', models.EmailField(db_column='CORREO', max_length=254, unique=True)),
                ('direccion', models.CharField(blank=True, db_column='DIRECCION', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, db_column='TELEFONO', max_length=20, null=True)),
                ('password', models.CharField(db_column='PASSWORD', max_length=255)),
                ('is_active', models.BooleanField(db_column='ACTIVO', default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rol', models.ForeignKey(db_column='ID_ROL', on_delete=django.db.models.deletion.PROTECT, to='reefapp.rol')),
            ],
            options={
                'db_table': 'USUARIO',
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_habitacion', models.AutoField(db_column='ID_HABITACION', primary_key=True, serialize=False)),
                ('numero', models.CharField(db_column='NUMERO', max_length=10, unique=True)),
                ('piso', models.IntegerField(db_column='PISO')),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('doble', 'Doble'), ('familiar', 'Familiar'), ('suiteD', 'SuiteD'), ('suiteF', 'SuiteF')], db_column='TIPO', max_length=20)),
                ('capacidad_adultos', models.IntegerField(db_column='CAPACIDAD_ADULTOS', default=1)),
                ('capacidad_ninos', models.IntegerField(db_column='CAPACIDAD_NINOS', default=0)),
                ('precio_base', models.DecimalField(db_column='PRECIO_BASE', decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('mantenimiento', 'Mantenimiento'), ('reservada', 'Reservada')], db_column='ESTADO', default='disponible', max_length=20)),
                ('descripcion', models.TextField(db_column='DESCRIPCION')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('categoria', models.ForeignKey(db_column='ID_CATEGORIA', on_delete=django.db.models.deletion.PROTECT, to='reefapp.categoriahabitacion')),
            ],
            options={
                'db_table': 'HABITACION',
            },
        ),
        migrations.CreateModel(
            name='HabitacionCaracteristica',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('caracteristica', models.ForeignKey(db_column='ID_CARACTERISTICA', on_delete=django.db.models.deletion.CASCADE, to='reefapp.caracteristicahabitacion')),
                ('habitacion', models.ForeignKey(db_column='ID_HABITACION', on_delete=django.db.models.deletion.CASCADE, to='reefapp.habitacion')),
            ],
            options={
                'db_table': 'HABITACION_CARACTERISTICA',
            },
        ),
        migrations.CreateModel(
            name='ImagenHabitacion',
            fields=[
                ('id_imagen', models.AutoField(db_column='ID_IMAGEN', primary_key=True, serialize=False)),
                ('imagen', models.ImageField(db_column='IMAGEN', upload_to='habitaciones/')),
                ('es_principal', models.BooleanField(db_column='ES_PRINCIPAL', default=False)),
                ('habitacion', models.ForeignKey(db_column='ID_HABITACION', on_delete=django.db.models.deletion.CASCADE, to='reefapp.habitacion')),
            ],
            options={
                'db_table': 'IMAGEN_HABITACION',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(db_column='ID_RESERVA', primary_key=True, serialize=False)),
                ('codigo_reserva', models.CharField(db_column='CODIGO_RESERVA', max_length=15, unique=True)),
                ('fecha_checkin', models.DateField(db_column='FECHA_CHECKIN')),
                ('fecha_checkout', models.DateField(db_column='FECHA_CHECKOUT')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, db_column='FECHA_RESERVA')),
                ('adultos', models.IntegerField(db_column='ADULTOS')),
                ('ninos', models.IntegerField(db_column='NINOS', default=0)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('activa', 'Activa'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], db_column='ESTADO', default='pendiente', max_length=20)),
                ('total', models.DecimalField(db_column='TOTAL', decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('cliente', models.ForeignKey(db_column='ID_CLIENTE', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('habitacion', models.ForeignKey(db_column='ID_HABITACION', on_delete=django.db.models.deletion.PROTECT, to='reefapp.habitacion')),
            ],
            options={
                'db_table': 'RESERVA',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(db_column='ID_PAGO', primary_key=True, serialize=False)),
                ('monto', models.DecimalField(db_column='MONTO', decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('transferencia', 'Transferencia Bancaria'), ('paypal', 'PayPal')], db_column='METODO_PAGO', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], db_column='ESTADO', default='pendiente', max_length=20)),
                ('fecha_pago', models.DateTimeField(blank=True, db_column='FECHA_PAGO', null=True)),
                ('transaccion_id', models.CharField(blank=True, db_column='TRANSACCION_ID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('reserva', models.ForeignKey(db_column='ID_RESERVA', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='reefapp.reserva')),
            ],
            options={
                'db_table': 'PAGO',
            },
        ),
    ]
