# Generated by Django 5.2.7 on 2025-10-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reefapp', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='total',
        ),
        migrations.AddField(
            model_name='reserva',
            name='pago_reserva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='total_estadia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
